#!/usr/bin/env python
# license removed for brevity
import rospy
from sensor_msgs.msg import Image
import cv2
from cv_bridge import CvBridge, CvBridgeError
import sys


def talker():
    video_capture = cv2.VideoCapture('video/tennis-ball-video.mp4')
    #create a new publisher. we specify the topic name, then type of message then the queue size
    pub = rospy.Publisher('tennis_ball_image',Image, queue_size=10)
   
    rospy.init_node('tennis_ball_listener', anonymous=True)
    #set the loop rate
    rate = rospy.Rate(50) # 1hz
    #keep publishing until a Ctrl-C is pressed
    
    i = 0
    while not rospy.is_shutdown():
        ret, frame = video_capture.read()
        br=CvBridge()
        try:
            frameRos = br.cv2_to_imgmsg(frame, "bgr8")
        except CvBridgeError as e:
            print(e)

        pub.publish(frameRos)
        rate.sleep()
        i=i+1

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
